export enum StatusHidupEnum {
  HIDUP = "HIDUP",
  MENINGGAL = "MENINGGAL",
}

export enum JenisKelaminEnum {
  LAKI_LAKI = "LAKI_LAKI",
  PEREMPUAN = "PEREMPUAN",
}

export enum Agama {
  KRISTEN = "KRISTEN",
  ISLAM = "ISLAM",
  KATOLIK = "KATOLIK",
  HINDU = "HINDU",
  BUDDHA = "BUDDHA",
  KHONGHUCU = "KHONGHUCU",
  LAINNYA = "LAINNYA",
}

export enum Pekerjaan {
  PELAJAR = "PELAJAR",
  MAHASISWA = "MAHASISWA",
  PETANI = "PETANI",
  NELAYAN = "NELAYAN",
  PEGAWAI_NEGERI = "PEGAWAI_NEGERI",
  KARYAWAN_SWASTA = "KARYAWAN_SWASTA",
  WIRASWASTA = "WIRASWASTA",
  GURU = "GURU",
  DOKTER = "DOKTER",
  IBU_RUMAH_TANGGA = "IBU_RUMAH_TANGGA",
  TIDAK_BEKERJA = "TIDAK_BEKERJA",
  LAINNYA = "LAINNYA",
}
